id: E212_MNC

title:
  en: >-
    Mobile Network Codes (MNC)
    for the international identification plan
    for public networks and subscriptions
  ru: >-
    Коды сетей подвижной связи (MNC)
    для плана международной идентификации
    для сетей общего пользования и абонентов

recommendation:
  body: ITU-T
  code: E.212
  version: 2016-09
